### ISSUE TITLE
Invalid message of nested error 

### ISSUE THREAD

**Issue by maranqz** [cockroachdb/errors#109]
Hello. Thank you for the Library and error handling RFC.

I have error ErrDB and the child of that ErrDBNotFound.
Then I enrich Err with stack and want to get message "db: not found", but I get "db".
I found that [`extractPrefix`](https://github.com/cockroachdb/errors/blob/26622367a22260fa287d2f7aa2a085b0324c74ee/errbase/encode.go#L165) cut the part of message, could you give advice how to fix it and why `extractPrefix` was added?

https://go.dev/play/p/gqT2QOTMcRn
```go
package main

import (
	"errors"
	"fmt"

	crerr "github.com/cockroachdb/errors"
)

var (
	ErrDB         = errors.New("db")
	ErrDBNotFound = fmt.Errorf("%w: not found", ErrDB)
)

func main() {
	err := ErrDBNotFound

	fmt.Println(errors.Is(ErrDBNotFound, ErrDB))
	fmt.Println(err.Error())

	errStl := crerr.WithStack(err)
	fmt.Println(errStl)

	// Output: true
	// db: not found
	// db

	// Want Output:
	// true
	// db: not found
	// db: not found
}

```

Solution, which I see, but I hope there is more elegant solution and explanation.
1. `fmt.Errorf("%w: %w", ErrDB, ErrDBNotFound)`
2. `WithMessage` or custom Err with changing `func Error() string`

**Comment by knz** [comment]
Try this:
```go
        ErrDBNotFound = fmt.Errorf("object not found: %w", ErrDB)
```

Alternatively, you can indeed add a custom error object:
```go
type notFound struct {
  error
}

// This is important.
func (e *notFound) FormatError(p errors.Printer) error {
  p.Printf("%s: not found", e.error.Error()) 
  return nil
}

func (e *notFound) Unwrap() error { return e.error }
func (e *notFound) Error() string { return fmt.Sprint(errors.Formattable(e)) }

var        ErrDBNotFound = &notFound{ErrDB}
```

**Comment by maranqz** [comment]
Thank you, but I want `db: not found` to show that `not found` is error of `db` like [`math/big: some error`](https://github.com/golang/go/blob/4859392cc29a35a0126e249ecdedbd022c755b20/src/math/big/ratmarsh.go#L83) or [`sql: some error`](https://github.com/golang/go/blob/374bd6a3ac7a201cfb37230942fedaa0451e4de6/src/database/sql/sql.go#L818) in built in libraries.

Why extractPrefix was added?
