### ISSUE TITLE
Incompatible implementation of Cause

### ISSUE THREAD

**Issue by polomsky** [cockroachdb/errors#15]
Hi.

It has different behaviour than `github.com/pkg/errors` (as reported as drop-in replacement).
Example code
```
e1 := errors.Wrap(io.EOF, "foobar")
e2 := errors.WithStack(e1)
fmt.Println(errors.Cause(e2))
fmt.Println(errors.Cause(e2) == io.EOF)
```

with `github.com/pkg/errors` the result is `EOF true`
with this library the result is `foobar: EOF false`.

The difference is that Cause in `github.com/pkg/errors` returns the deepest error.

**Comment by knz** [comment]
I am so sorry we did not see your report earlier. Very good find.
Fixed in #17.
