### ISSUE TITLE
AssertionFailedf (and maybe others) is too strict

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/errors#16]
Mess up the format string/args of `AssertionFailedf` and you get (at runtime): `AssertionFailedf format %s reads arg #1, but call has 0 args`, and no more info about the assertion in question.
This is not great because what you want to get when an assertion failed is whatever info is available (i.e. the format string and the args that were there). A lot of assertions are not tested, so there's no opportunity for programmers to fix these errors.
For example, the go stdlib is more permissive here.

**Comment by knz** [comment]
Can you provide more details? The formatting is handled via the go stdlib - there is no custom code in the `errors` library to handle formatting. I find it surprising that there is a separate code path in the go stdlib for this and I would like to investigate this.

**Comment by knz** [comment]
We've fixed a couple of errors due to the argument list. Feel free to file a new issue if you observe something new.
