### ISSUE TITLE
Go modules

### ISSUE THREAD

**Issue by LasTshaMAN** [cockroachdb/errors#2]
Are there any plans for adding go modules to the package itself ?

It would simplify further contributions to this package.

**Comment by sagikazarmark** [comment]
I would like to add that extracting the Sentry support to an external package might make sense to keep this library dependency free.

**Comment by knz** [comment]
- for go modules: we welcome contributions
- moving sentry support elsewhere: why is this important?

**Comment by sagikazarmark** [comment]
A large number of the features of this library are generic purpose helpers for creating and handling errors. Those who don't want to use Sentry or protobuf serialization still have to install those dependencies. That might drive away some people from your library.

**Comment by knz** [comment]
I'm sure that those who don't want to use Sentry can fork the errors library and remove the file `report_api.go` from the top level directory, this will be  sufficient to drop the dependency.

As for protobuf serialization, well, you probably understand that this is not really something that can be dropped.

**Comment by sagikazarmark** [comment]
Sure, I understand that. Just wanted to point out a common pain point for users when using Go modules.

**Comment by knz** [comment]
Thanks for pointing it out.

**Comment by simar7** [comment]
I've added go mod support to get things started in this PR: https://github.com/cockroachdb/errors/pull/4 

Thank you for open sourcing this project! Looking forward to playing with it.
