### ISSUE TITLE
Requires use of github.com/cockroachdb/sentry-go

### ISSUE THREAD

**Issue by mikesun** [cockroachdb/errors#36]
This package uses its own fork of [sentry-go](https://github.com/getsentry/sentry-go) which means a user of this package has to use the forked version when initializing the sentry client. Is that the accepted practice around this?

**Comment by knz** [comment]
I don't know what the accepted practice is. Do you have a better suggestion?

**Comment by jhchabran** [comment]
Hello @knz, I was checking the dependencies in one of the projects I work on, spotted the old sentry-go version and ended up here. 

Seeing this [diff](https://github.com/getsentry/sentry-go/compare/master...cockroachdb:master) my best guess is that on some occasions, it has been useful to jump ahead and pin the dependencies at on a specific commit on the `master` branch. 

Would you want something done about it?

1. Drop the fork and update `errors` to use directly `getsentry/sentry-go` 
2. Keep the fork, but just update it, as mentioned in #41, just going up to v0.11.0. 
3. Something else? 

Reading through their [changelog](https://github.com/getsentry/sentry-go/blob/master/CHANGELOG.md), there are no mentions of any breaking changes.
