### ISSUE TITLE
Semantic Version Tagging

### ISSUE THREAD

**Issue by tooolbox** [cockroachdb/errors#37]
Go Modules requires that modules have fully qualified semver tags.  For example, I can't specify `v1.4` for cockroachdb/errors.  It would need to be `v1.4.0`.

This issue is to request that future tags be full three-part semver tags.  Thanks!

**Comment by knz** [comment]
Would it make sense to issue 3-part version tags for all previous releases as well?

**Comment by tooolbox** [comment]
I would say yes, just in case people need to pin to those&mdash;and as along as it doesn't take a lot of effort from you, which I don't think it should.

**Comment by knz** [comment]
I sent the `.0` tags for past releases today. Will keep in mind in the next release.
