### ISSUE TITLE
Best way to allow strings in error object in reports

### ISSUE THREAD

**Issue by mikesun** [cockroachdb/errors#38]
https://github.com/cockroachdb/errors#providing-pii-free-details
> by default, strings included in an error object are considered to be PII-unsafe, and are stripped out when building a Sentry report.

What would be the best/easiest way to allow error object strings *not* to be stripped out from Sentry reports? When I use this package to wrap errors from other packages that don't include stack traces, I'd like to have the error strings be included in Sentry reports.

**Comment by knz** [comment]
we now support the `redact` features inside error objects.
