### ISSUE TITLE
Clarify PII-related Breaking Change in v1.6.0

### ISSUE THREAD

**Issue by tooolbox** [cockroachdb/errors#44]
I saw the release of [v1.6.0](https://github.com/cockroachdb/errors/releases/tag/v1.6.0) which states:

> The errors.New(), errors.NewWithDepth(), errors.Wrap() and
errors.WrapWithDepth() now consider their string argument as
PII-free, and the string is now also included in Sentry reports.

What I get is that the string arguments to these functions are *not* expected to have PII in them and therefore will not be redacted when submitting to Sentry.

> This is a breaking change if your code uses the included
Sentry reporting: in previous versions, only the format
argument to errors.Newf, errors.Wrapf etc was considered to be
PII-free and non-reportable. With the new version, more strings
are reportable.

This seems contradictory.  PII-free *and* non-reportable?  You mean PII-free and reportable?

The readme may require some updating: https://github.com/cockroachdb/errors#providing-pii-free-details

Also, some more examples in that section would be appreciated if you have the time.  The listing is very detailed, but some concrete examples wouldn't be remiss, i.e. showing some mock code that is handling user data, it encounters an error, and how the error is wrapped and returned and detailed and telemetried such that it provides context without PII.  I'm also curious what differentiation you make between Sentry reports and plain old log files.

Thanks for the great stewardship!

**Comment by knz** [comment]
> I saw the release of [v1.6.0](https://github.com/cockroachdb/errors/releases/tag/v1.6.0) which states: [..]
> What I get is that the string arguments to these functions are _not_ expected to have PII in them and therefore will not be redacted when submitting to Sentry.
>  [...]
> This seems contradictory. PII-free _and_ non-reportable? You mean PII-free and reportable?

Good comment. Changed this as follows:
![image](https://user-images.githubusercontent.com/642886/90771069-0a8a7d80-e2f3-11ea-8062-c4c7c39bf7c1.png)

Let me know if this needs to be enhanced further.

> The readme may require some updating: [cockroachdb/errors#providing-pii-free-details](https://github.com/cockroachdb/errors#providing-pii-free-details)

good point, will do


> Also, some more examples in that section would be appreciated if you have the time. The listing is very detailed, but some concrete examples wouldn't be remiss, 

I think I'd prefer to do this with a series of blog posts. Also I have a new test engine coming which will do a better job of explaining by example. Will ping you on this.

**Comment by knz** [comment]
> good point, will do

Done

**Comment by tooolbox** [comment]
> Good comment. Changed this as follows:

Definitely more clear, thanks.

> Done

The README looks great and I have a much better concept on the PII handling!

> I think I'd prefer to do this with a series of blog posts. Also I have a new test engine coming which will do a better job of explaining by example. Will ping you on this.

Awesome, looking forward to it.
