### ISSUE TITLE
compared to hashicorp/go-multierror

### ISSUE THREAD

**Issue by xmlking** [cockroachdb/errors#50]
wonder how this package compared to  https://github.com/hashicorp/go-multierror ?
do I need `hashicorp/go-multierror`  if I use `cockroachdb/errors`?

**Comment by tooolbox** [comment]
Generally speaking, no.  There may be a few minor things that the Hashicorp package has that the Cockroachdb one doesn't, but at a glance I'd say the scales are very tipped the other direction.

**Comment by knz** [comment]
I'll proceed to close the issue since the discussion seems finished. Feel free to re-open otherwise.
