### ISSUE TITLE
Investigate whether there is fallout from #60

### ISSUE THREAD

**Issue by knz** [cockroachdb/errors#61]
@tooolbox pointed out helpfully that #60 may have changed the protobuf package paths and thus the encoding of errors over the network.

This needs to be checked in a test. If there is any discrepancy, that needs to be dealt with a proper `RegisterTypeMigration` call.

**Comment by knz** [comment]
I have investigated this by looking at the binary protobuf encoding of test errors.

The protobuf package path is unchanged and remains `cockroachdb.errorspb`. There is no change in the binary encoding. So #60 does not require any change in apps.

Thanks @tooolbox for asking nevertheless.

**Comment by tooolbox** [comment]
No problem, thanks for checking it out!
