### ISSUE TITLE
Is this space in the formatting verb correct?

### ISSUE THREAD

**Issue by StevenACoffman** [cockroachdb/errors#93]
Sorry, but my reading of the code, can you confirm whether the space character is intended?
I would think that `"%# v"` should instead be `"%#v"` in:
https://github.com/cockroachdb/errors/blob/master/errbase/format_error.go#L122

> Go offers several printing “verbs” designed to format general Go values. 
> 
> If the value is a struct, the `%+v` variant will include the struct’s field names.
> The `%#v` variant prints a Go syntax representation of the value, i.e. the source code snippet that would produce that value.

**Comment by knz** [comment]
Yes it is correct, it's a special flag recognized by the kr/pretty library.

**Comment by StevenACoffman** [comment]
Thanks!
