### ISSUE TITLE
Question: Will support Go 1.20: wrapping multiple errors?

### ISSUE THREAD

**Issue by nebiros** [cockroachdb/errors#99]
Will support Go 1.20: wrapping multiple errors?

**Comment by StevenACoffman** [comment]
Go 1.20 also brings:
* pkg fmt, func FormatString(State, int32) string

which should simplify format forwarding in this library.

**Comment by dhartunian** [comment]
Go 1.20 and multi-cause error support has been released! Appreciate everyone's patience.

https://github.com/cockroachdb/errors/releases/tag/v1.11.0
